@baseUrl = http://localhost:3000
### Hello
GET {{baseUrl}}/

### Listar libros
GET {{baseUrl}}/api/libros

### Libros disponibles
GET {{baseUrl}}/api/libros?disponible=true

@baseUrl = http://localhost:3000
### Hello
GET {{baseUrl}}/

### Listar libros
GET {{baseUrl}}/api/libros

### Autores
GET {{baseUrl}}/api/autores/2

### Libros disponibles
GET {{baseUrl}}/api/libros?disponible=true

### Un libro
GET {{baseUrl}}/api/libros/1

### Un libro que no existe → 404
GET {{baseUrl}}/api/libros/999

### Crear un libro
POST {{baseUrl}}/api/libros